# coding: utf-8

"""
    Endpoints

    Oyster uses OAuth2 to enable customers to grant access to their data to third party applications. Customers also need to use this API to authenticate themselves when making API requests.

    The version of the OpenAPI document: v1
    Generated by: https://konfigthis.com
"""

import unittest

import os
from pprint import pprint
from oyster_python_sdk import Oyster

class TestSimple(unittest.TestCase):
    def setUp(self):
        pass

    def test_client(self):
        oyster = Oyster(
        
            access_token = 'YOUR_BEARER_TOKEN'
        )
        self.assertIsNotNone(oyster)

    def tearDown(self):
        pass


if __name__ == "__main__":
    unittest.main()
