# coding: utf-8

# flake8: noqa

"""
    Endpoints

    Oyster uses OAuth2 to enable customers to grant access to their data to third party applications. Customers also need to use this API to authenticate themselves when making API requests.

    The version of the OpenAPI document: v1
    Generated by: https://konfigthis.com
"""

__version__ = "v1"

# import ApiClient
from oyster_python_sdk.api_client import ApiClient

# import Configuration
from oyster_python_sdk.configuration import Configuration

# import exceptions
from oyster_python_sdk.exceptions import OpenApiException
from oyster_python_sdk.exceptions import ApiAttributeError
from oyster_python_sdk.exceptions import ApiTypeError
from oyster_python_sdk.exceptions import ApiValueError
from oyster_python_sdk.exceptions import ApiKeyError
from oyster_python_sdk.exceptions import ApiException

from oyster_python_sdk.client import Oyster
