# coding: utf-8
"""
    Endpoints

    Oyster uses OAuth2 to enable customers to grant access to their data to third party applications. Customers also need to use this API to authenticate themselves when making API requests.

    The version of the OpenAPI document: v1
    Generated by: https://konfigthis.com
"""

import typing
import inspect
from datetime import date, datetime
from oyster_python_sdk.client_custom import ClientCustom
from oyster_python_sdk.configuration import Configuration
from oyster_python_sdk.api_client import ApiClient
from oyster_python_sdk.type_util import copy_signature
from oyster_python_sdk.apis.tags.authentication_api import AuthenticationApi
from oyster_python_sdk.apis.tags.company_api import CompanyApi
from oyster_python_sdk.apis.tags.departments_api import DepartmentsApi
from oyster_python_sdk.apis.tags.engagements_api import EngagementsApi
from oyster_python_sdk.apis.tags.expenses_api import ExpensesApi
from oyster_python_sdk.apis.tags.operations_api import OperationsApi
from oyster_python_sdk.apis.tags.payroll_api import PayrollApi
from oyster_python_sdk.apis.tags.time_off_api import TimeOffApi



class Oyster(ClientCustom):

    def __init__(self, configuration: typing.Union[Configuration, None] = None, **kwargs):
        super().__init__(configuration, **kwargs)
        if (len(kwargs) > 0):
            configuration = Configuration(**kwargs)
        if (configuration is None):
            raise Exception("configuration is required")
        api_client = ApiClient(configuration)
        self.authentication: AuthenticationApi = AuthenticationApi(api_client)
        self.company: CompanyApi = CompanyApi(api_client)
        self.departments: DepartmentsApi = DepartmentsApi(api_client)
        self.engagements: EngagementsApi = EngagementsApi(api_client)
        self.expenses: ExpensesApi = ExpensesApi(api_client)
        self.operations: OperationsApi = OperationsApi(api_client)
        self.payroll: PayrollApi = PayrollApi(api_client)
        self.time_off: TimeOffApi = TimeOffApi(api_client)
