# coding: utf-8

"""
    Endpoints

    Oyster uses OAuth2 to enable customers to grant access to their data to third party applications. Customers also need to use this API to authenticate themselves when making API requests.

    The version of the OpenAPI document: v1
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from oyster_python_sdk import schemas  # noqa: F401


class Payroll(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        required = {
            "payrollRecordsCount",
            "cutoffTimeForPayroll",
            "payrollId",
            "state",
            "currencyCode",
        }
        
        class properties:
            payrollId = schemas.StrSchema
            currencyCode = schemas.StrSchema
            
            
            class cutoffTimeForPayroll(
                schemas.DateTimeBase,
                schemas.StrBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneStrMixin
            ):
            
            
                class MetaOapg:
                    format = 'date-time'
            
            
                def __new__(
                    cls,
                    *args: typing.Union[None, str, datetime, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'cutoffTimeForPayroll':
                    return super().__new__(
                        cls,
                        *args,
                        _configuration=_configuration,
                    )
            state = schemas.StrSchema
            payrollRecordsCount = schemas.IntSchema
            
            
            class records(
                schemas.ListSchema
            ):
            
            
                class MetaOapg:
                    
                    @staticmethod
                    def items() -> typing.Type['PayrollRecord']:
                        return PayrollRecord
            
                def __new__(
                    cls,
                    arg: typing.Union[typing.Tuple['PayrollRecord'], typing.List['PayrollRecord']],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'records':
                    return super().__new__(
                        cls,
                        arg,
                        _configuration=_configuration,
                    )
            
                def __getitem__(self, i: int) -> 'PayrollRecord':
                    return super().__getitem__(i)
            __annotations__ = {
                "payrollId": payrollId,
                "currencyCode": currencyCode,
                "cutoffTimeForPayroll": cutoffTimeForPayroll,
                "state": state,
                "payrollRecordsCount": payrollRecordsCount,
                "records": records,
            }
    
    payrollRecordsCount: MetaOapg.properties.payrollRecordsCount
    cutoffTimeForPayroll: MetaOapg.properties.cutoffTimeForPayroll
    payrollId: MetaOapg.properties.payrollId
    state: MetaOapg.properties.state
    currencyCode: MetaOapg.properties.currencyCode
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["payrollId"]) -> MetaOapg.properties.payrollId: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["currencyCode"]) -> MetaOapg.properties.currencyCode: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["cutoffTimeForPayroll"]) -> MetaOapg.properties.cutoffTimeForPayroll: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["state"]) -> MetaOapg.properties.state: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["payrollRecordsCount"]) -> MetaOapg.properties.payrollRecordsCount: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["records"]) -> MetaOapg.properties.records: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["payrollId", "currencyCode", "cutoffTimeForPayroll", "state", "payrollRecordsCount", "records", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["payrollId"]) -> MetaOapg.properties.payrollId: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["currencyCode"]) -> MetaOapg.properties.currencyCode: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["cutoffTimeForPayroll"]) -> MetaOapg.properties.cutoffTimeForPayroll: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["state"]) -> MetaOapg.properties.state: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["payrollRecordsCount"]) -> MetaOapg.properties.payrollRecordsCount: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["records"]) -> typing.Union[MetaOapg.properties.records, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["payrollId", "currencyCode", "cutoffTimeForPayroll", "state", "payrollRecordsCount", "records", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        payrollRecordsCount: typing.Union[MetaOapg.properties.payrollRecordsCount, decimal.Decimal, int, ],
        cutoffTimeForPayroll: typing.Union[MetaOapg.properties.cutoffTimeForPayroll, None, str, datetime, ],
        payrollId: typing.Union[MetaOapg.properties.payrollId, str, ],
        state: typing.Union[MetaOapg.properties.state, str, ],
        currencyCode: typing.Union[MetaOapg.properties.currencyCode, str, ],
        records: typing.Union[MetaOapg.properties.records, list, tuple, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'Payroll':
        return super().__new__(
            cls,
            *args,
            payrollRecordsCount=payrollRecordsCount,
            cutoffTimeForPayroll=cutoffTimeForPayroll,
            payrollId=payrollId,
            state=state,
            currencyCode=currencyCode,
            records=records,
            _configuration=_configuration,
            **kwargs,
        )

from oyster_python_sdk.model.payroll_record import PayrollRecord
