# coding: utf-8

"""
    Endpoints

    Oyster uses OAuth2 to enable customers to grant access to their data to third party applications. Customers also need to use this API to authenticate themselves when making API requests.

    The version of the OpenAPI document: v1
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from oyster_python_sdk import schemas  # noqa: F401


class PayrollRecord(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        required = {
            "monthlyPaymentsTotalAmount",
            "bonusesTotalAmount",
            "engagement",
            "oysterFeesTotalAmount",
            "addOnsTotalAmount",
            "trueUpsTotalAmount",
            "benefitsTotalAmount",
            "allowancesTotalAmount",
            "taxesTotalAmount",
            "currencyCode",
            "engagementId",
        }
        
        class properties:
            engagementId = schemas.StrSchema
            currencyCode = schemas.StrSchema
        
            @staticmethod
            def monthlyPaymentsTotalAmount() -> typing.Type['Amount']:
                return Amount
        
            @staticmethod
            def allowancesTotalAmount() -> typing.Type['Amount']:
                return Amount
        
            @staticmethod
            def benefitsTotalAmount() -> typing.Type['Amount']:
                return Amount
        
            @staticmethod
            def bonusesTotalAmount() -> typing.Type['Amount']:
                return Amount
        
            @staticmethod
            def addOnsTotalAmount() -> typing.Type['Amount']:
                return Amount
        
            @staticmethod
            def taxesTotalAmount() -> typing.Type['Amount']:
                return Amount
        
            @staticmethod
            def trueUpsTotalAmount() -> typing.Type['Amount']:
                return Amount
        
            @staticmethod
            def oysterFeesTotalAmount() -> typing.Type['Amount']:
                return Amount
        
            @staticmethod
            def engagement() -> typing.Type['PayrollRecordEngagement']:
                return PayrollRecordEngagement
            __annotations__ = {
                "engagementId": engagementId,
                "currencyCode": currencyCode,
                "monthlyPaymentsTotalAmount": monthlyPaymentsTotalAmount,
                "allowancesTotalAmount": allowancesTotalAmount,
                "benefitsTotalAmount": benefitsTotalAmount,
                "bonusesTotalAmount": bonusesTotalAmount,
                "addOnsTotalAmount": addOnsTotalAmount,
                "taxesTotalAmount": taxesTotalAmount,
                "trueUpsTotalAmount": trueUpsTotalAmount,
                "oysterFeesTotalAmount": oysterFeesTotalAmount,
                "engagement": engagement,
            }
    
    monthlyPaymentsTotalAmount: 'Amount'
    bonusesTotalAmount: 'Amount'
    engagement: 'PayrollRecordEngagement'
    oysterFeesTotalAmount: 'Amount'
    addOnsTotalAmount: 'Amount'
    trueUpsTotalAmount: 'Amount'
    benefitsTotalAmount: 'Amount'
    allowancesTotalAmount: 'Amount'
    taxesTotalAmount: 'Amount'
    currencyCode: MetaOapg.properties.currencyCode
    engagementId: MetaOapg.properties.engagementId
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["engagementId"]) -> MetaOapg.properties.engagementId: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["currencyCode"]) -> MetaOapg.properties.currencyCode: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["monthlyPaymentsTotalAmount"]) -> 'Amount': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["allowancesTotalAmount"]) -> 'Amount': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["benefitsTotalAmount"]) -> 'Amount': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["bonusesTotalAmount"]) -> 'Amount': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["addOnsTotalAmount"]) -> 'Amount': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["taxesTotalAmount"]) -> 'Amount': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["trueUpsTotalAmount"]) -> 'Amount': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["oysterFeesTotalAmount"]) -> 'Amount': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["engagement"]) -> 'PayrollRecordEngagement': ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["engagementId", "currencyCode", "monthlyPaymentsTotalAmount", "allowancesTotalAmount", "benefitsTotalAmount", "bonusesTotalAmount", "addOnsTotalAmount", "taxesTotalAmount", "trueUpsTotalAmount", "oysterFeesTotalAmount", "engagement", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["engagementId"]) -> MetaOapg.properties.engagementId: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["currencyCode"]) -> MetaOapg.properties.currencyCode: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["monthlyPaymentsTotalAmount"]) -> 'Amount': ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["allowancesTotalAmount"]) -> 'Amount': ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["benefitsTotalAmount"]) -> 'Amount': ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["bonusesTotalAmount"]) -> 'Amount': ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["addOnsTotalAmount"]) -> 'Amount': ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["taxesTotalAmount"]) -> 'Amount': ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["trueUpsTotalAmount"]) -> 'Amount': ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["oysterFeesTotalAmount"]) -> 'Amount': ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["engagement"]) -> 'PayrollRecordEngagement': ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["engagementId", "currencyCode", "monthlyPaymentsTotalAmount", "allowancesTotalAmount", "benefitsTotalAmount", "bonusesTotalAmount", "addOnsTotalAmount", "taxesTotalAmount", "trueUpsTotalAmount", "oysterFeesTotalAmount", "engagement", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        monthlyPaymentsTotalAmount: 'Amount',
        bonusesTotalAmount: 'Amount',
        engagement: 'PayrollRecordEngagement',
        oysterFeesTotalAmount: 'Amount',
        addOnsTotalAmount: 'Amount',
        trueUpsTotalAmount: 'Amount',
        benefitsTotalAmount: 'Amount',
        allowancesTotalAmount: 'Amount',
        taxesTotalAmount: 'Amount',
        currencyCode: typing.Union[MetaOapg.properties.currencyCode, str, ],
        engagementId: typing.Union[MetaOapg.properties.engagementId, str, ],
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'PayrollRecord':
        return super().__new__(
            cls,
            *args,
            monthlyPaymentsTotalAmount=monthlyPaymentsTotalAmount,
            bonusesTotalAmount=bonusesTotalAmount,
            engagement=engagement,
            oysterFeesTotalAmount=oysterFeesTotalAmount,
            addOnsTotalAmount=addOnsTotalAmount,
            trueUpsTotalAmount=trueUpsTotalAmount,
            benefitsTotalAmount=benefitsTotalAmount,
            allowancesTotalAmount=allowancesTotalAmount,
            taxesTotalAmount=taxesTotalAmount,
            currencyCode=currencyCode,
            engagementId=engagementId,
            _configuration=_configuration,
            **kwargs,
        )

from oyster_python_sdk.model.amount import Amount
from oyster_python_sdk.model.payroll_record_engagement import PayrollRecordEngagement
