# coding: utf-8

"""
    Endpoints

    Oyster uses OAuth2 to enable customers to grant access to their data to third party applications. Customers also need to use this API to authenticate themselves when making API requests.

    The version of the OpenAPI document: v1
    Generated by: https://konfigthis.com
"""

import unittest

import oyster_python_sdk
from oyster_python_sdk.model.time_off_engagement_details import TimeOffEngagementDetails
from oyster_python_sdk import configuration


class TestTimeOffEngagementDetails(unittest.TestCase):
    """TimeOffEngagementDetails unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
