# coding: utf-8

"""
    Endpoints

    Oyster uses OAuth2 to enable customers to grant access to their data to third party applications. Customers also need to use this API to authenticate themselves when making API requests.

    The version of the OpenAPI document: v1
    Generated by: https://konfigthis.com
"""

import unittest

import oyster_python_sdk
from oyster_python_sdk.model.operations_get_by_operation_key_response import OperationsGetByOperationKeyResponse
from oyster_python_sdk import configuration


class TestOperationsGetByOperationKeyResponse(unittest.TestCase):
    """OperationsGetByOperationKeyResponse unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
