# coding: utf-8

"""
    Endpoints

    Oyster uses OAuth2 to enable customers to grant access to their data to third party applications. Customers also need to use this API to authenticate themselves when making API requests.

    The version of the OpenAPI document: v1
    Generated by: https://konfigthis.com
"""

from oyster_python_sdk.paths.v1_departments.get import GetAll
from oyster_python_sdk.apis.tags.departments_api_raw import DepartmentsApiRaw


class DepartmentsApi(
    GetAll,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: DepartmentsApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = DepartmentsApiRaw(api_client)
