# coding: utf-8

"""
    Endpoints

    Oyster uses OAuth2 to enable customers to grant access to their data to third party applications. Customers also need to use this API to authenticate themselves when making API requests.

    The version of the OpenAPI document: v1
    Generated by: https://konfigthis.com
"""

from oyster_python_sdk.paths.v1_engagements.get import GetAllRaw
from oyster_python_sdk.paths.v1_engagements_id.get import GetByIdRaw


class EngagementsApiRaw(
    GetAllRaw,
    GetByIdRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
