# coding: utf-8

"""
    Endpoints

    Oyster uses OAuth2 to enable customers to grant access to their data to third party applications. Customers also need to use this API to authenticate themselves when making API requests.

    The version of the OpenAPI document: v1
    Generated by: https://konfigthis.com
"""

from oyster_python_sdk.paths.v1_expenses_id_approve.post import ApproveExpense
from oyster_python_sdk.paths.v1_expenses.post import CreateOperationKey
from oyster_python_sdk.paths.v1_expenses_id_decline.post import DeclineExpense
from oyster_python_sdk.paths.v1_expenses_id.get import GetById
from oyster_python_sdk.apis.tags.expenses_api_raw import ExpensesApiRaw


class ExpensesApi(
    ApproveExpense,
    CreateOperationKey,
    DeclineExpense,
    GetById,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: ExpensesApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = ExpensesApiRaw(api_client)
