# coding: utf-8

"""
    Endpoints

    Oyster uses OAuth2 to enable customers to grant access to their data to third party applications. Customers also need to use this API to authenticate themselves when making API requests.

    The version of the OpenAPI document: v1
    Generated by: https://konfigthis.com
"""

from oyster_python_sdk.paths.v1_payroll.get import GetAllPayrolls
from oyster_python_sdk.paths.v1_payroll_id.get import GetById
from oyster_python_sdk.apis.tags.payroll_api_raw import PayrollApiRaw


class PayrollApi(
    GetAllPayrolls,
    GetById,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: PayrollApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = PayrollApiRaw(api_client)
