# coding: utf-8

"""
    Endpoints

    Oyster uses OAuth2 to enable customers to grant access to their data to third party applications. Customers also need to use this API to authenticate themselves when making API requests.

    The version of the OpenAPI document: v1
    Generated by: https://konfigthis.com
"""

from oyster_python_sdk.paths.v1_time_off_requests_id_approve.post import ApproveRequestRaw
from oyster_python_sdk.paths.v1_time_off_requests.get import GetAllRequestsRaw
from oyster_python_sdk.paths.v1_time_off_entitlements.get import GetEntitlementsRaw
from oyster_python_sdk.paths.v1_time_off_requests_id.get import GetRequestRaw
from oyster_python_sdk.paths.v1_time_off_requests_id_reject.post import RejectRequestRaw


class TimeOffApiRaw(
    ApproveRequestRaw,
    GetAllRequestsRaw,
    GetEntitlementsRaw,
    GetRequestRaw,
    RejectRequestRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
