# coding: utf-8

"""
    Endpoints

    Oyster uses OAuth2 to enable customers to grant access to their data to third party applications. Customers also need to use this API to authenticate themselves when making API requests.

    The version of the OpenAPI document: v1
    Generated by: https://konfigthis.com
"""

from oyster_python_sdk.paths.v1_time_off_requests_id_approve.post import ApproveRequest
from oyster_python_sdk.paths.v1_time_off_requests.get import GetAllRequests
from oyster_python_sdk.paths.v1_time_off_entitlements.get import GetEntitlements
from oyster_python_sdk.paths.v1_time_off_requests_id.get import GetRequest
from oyster_python_sdk.paths.v1_time_off_requests_id_reject.post import RejectRequest
from oyster_python_sdk.apis.tags.time_off_api_raw import TimeOffApiRaw


class TimeOffApi(
    ApproveRequest,
    GetAllRequests,
    GetEntitlements,
    GetRequest,
    RejectRequest,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: TimeOffApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = TimeOffApiRaw(api_client)
