# coding: utf-8

"""
    Endpoints

    Oyster uses OAuth2 to enable customers to grant access to their data to third party applications. Customers also need to use this API to authenticate themselves when making API requests.

    The version of the OpenAPI document: v1
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from oyster_python_sdk.type.engagement_benefit_enrollments import EngagementBenefitEnrollments
from oyster_python_sdk.type.engagement_department import EngagementDepartment
from oyster_python_sdk.type.engagement_personal_details import EngagementPersonalDetails
from oyster_python_sdk.type.engagement_terminations import EngagementTerminations

class RequiredEngagement(TypedDict):
    engagementId: str

    startDate: date

    engagementType: str

    role: str

    countryCode: str

    personalDetails: EngagementPersonalDetails

class OptionalEngagement(TypedDict, total=False):
    modifiedAt: datetime

    state: str

    employment: typing.Optional[typing.Dict[str, typing.Union[bool, date, datetime, dict, float, int, list, str, None]]]

    contract: typing.Optional[typing.Dict[str, typing.Union[bool, date, datetime, dict, float, int, list, str, None]]]

    benefitEnrollments: EngagementBenefitEnrollments

    terminations: EngagementTerminations

    department: typing.Optional[EngagementDepartment]

class Engagement(RequiredEngagement, OptionalEngagement):
    pass
