# coding: utf-8

"""
    Endpoints

    Oyster uses OAuth2 to enable customers to grant access to their data to third party applications. Customers also need to use this API to authenticate themselves when making API requests.

    The version of the OpenAPI document: v1
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from oyster_python_sdk.type.engagement_personal_details_addresses import EngagementPersonalDetailsAddresses
from oyster_python_sdk.type.engagement_personal_details_citizenships import EngagementPersonalDetailsCitizenships
from oyster_python_sdk.type.engagement_personal_details_phone_numbers import EngagementPersonalDetailsPhoneNumbers

class RequiredEngagementPersonalDetails(TypedDict):
    name: typing.Optional[str]

    addresses: EngagementPersonalDetailsAddresses

class OptionalEngagementPersonalDetails(TypedDict, total=False):
    citizenships: EngagementPersonalDetailsCitizenships

    dateOfBirth: typing.Optional[str]

    phoneNumbers: EngagementPersonalDetailsPhoneNumbers

class EngagementPersonalDetails(RequiredEngagementPersonalDetails, OptionalEngagementPersonalDetails):
    pass
