# coding: utf-8

"""
    Endpoints

    Oyster uses OAuth2 to enable customers to grant access to their data to third party applications. Customers also need to use this API to authenticate themselves when making API requests.

    The version of the OpenAPI document: v1
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from oyster_python_sdk.type.expenses_create_operation_key_request_receipt_amount import ExpensesCreateOperationKeyRequestReceiptAmount

class RequiredExpensesCreateOperationKeyRequest(TypedDict):
    engagementId: str

    name: str

    incurredOn: date

    category: str

    receiptUrl: str

    receiptAmount: ExpensesCreateOperationKeyRequestReceiptAmount

class OptionalExpensesCreateOperationKeyRequest(TypedDict, total=False):
    description: str

class ExpensesCreateOperationKeyRequest(RequiredExpensesCreateOperationKeyRequest, OptionalExpensesCreateOperationKeyRequest):
    pass
