# coding: utf-8

"""
    Endpoints

    Oyster uses OAuth2 to enable customers to grant access to their data to third party applications. Customers also need to use this API to authenticate themselves when making API requests.

    The version of the OpenAPI document: v1
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from oyster_python_sdk.type.meta import Meta
from oyster_python_sdk.type.time_off_requests import TimeOffRequests

class RequiredTimeOffGetAllRequestsResponse(TypedDict):
    data: TimeOffRequests

    meta: Meta

class OptionalTimeOffGetAllRequestsResponse(TypedDict, total=False):
    pass

class TimeOffGetAllRequestsResponse(RequiredTimeOffGetAllRequestsResponse, OptionalTimeOffGetAllRequestsResponse):
    pass
