# coding: utf-8

"""
    Endpoints

    Oyster uses OAuth2 to enable customers to grant access to their data to third party applications. Customers also need to use this API to authenticate themselves when making API requests.

    The version of the OpenAPI document: v1
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from oyster_python_sdk.type.time_off_engagement_details import TimeOffEngagementDetails

class RequiredTimeOffEntitlementsItem(TypedDict):
    pass

class OptionalTimeOffEntitlementsItem(TypedDict, total=False):
    engagement: TimeOffEngagementDetails

    annualEntitlement: typing.Union[int, float]

    accrued: typing.Union[int, float]

    carried: typing.Union[int, float]

    adjustedAdhoc: typing.Union[int, float]

    taken: typing.Union[int, float]

    availableBalance: typing.Union[int, float]

    upcoming: typing.Union[int, float]

    projectedBalance: typing.Union[int, float]

    units: str

class TimeOffEntitlementsItem(RequiredTimeOffEntitlementsItem, OptionalTimeOffEntitlementsItem):
    pass
