# coding: utf-8

"""
    Endpoints

    Oyster uses OAuth2 to enable customers to grant access to their data to third party applications. Customers also need to use this API to authenticate themselves when making API requests.

    The version of the OpenAPI document: v1
    Generated by: https://konfigthis.com
"""

import unittest
from unittest.mock import patch

import urllib3

import oyster_python_sdk
from oyster_python_sdk.paths.oauth2_token import post
from oyster_python_sdk import configuration, schemas, api_client

from .. import ApiTestMixin


class TestOauth2Token(ApiTestMixin, unittest.TestCase):
    """
    Oauth2Token unit test stubs
        Create an access token
    """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    response_status = 201






if __name__ == '__main__':
    unittest.main()
