# coding: utf-8

"""
    Endpoints

    Oyster uses OAuth2 to enable customers to grant access to their data to third party applications. Customers also need to use this API to authenticate themselves when making API requests.

    The version of the OpenAPI document: v1
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict

from oyster_python_sdk.pydantic.engagement_benefit_enrollments import EngagementBenefitEnrollments
from oyster_python_sdk.pydantic.engagement_department import EngagementDepartment
from oyster_python_sdk.pydantic.engagement_personal_details import EngagementPersonalDetails
from oyster_python_sdk.pydantic.engagement_terminations import EngagementTerminations

class Engagement(BaseModel):
    engagement_id: str = Field(alias='engagementId')

    start_date: date = Field(alias='startDate')

    engagement_type: Literal["EMPLOYMENT", "CONTRACT"] = Field(alias='engagementType')

    role: str = Field(alias='role')

    country_code: str = Field(alias='countryCode')

    personal_details: EngagementPersonalDetails = Field(alias='personalDetails')

    modified_at: typing.Optional[datetime] = Field(None, alias='modifiedAt')

    state: typing.Optional[str] = Field(None, alias='state')

    employment: typing.Optional[typing.Optional[typing.Dict[str, typing.Union[bool, date, datetime, dict, float, int, list, str, None]]]] = Field(None, alias='employment')

    contract: typing.Optional[typing.Optional[typing.Dict[str, typing.Union[bool, date, datetime, dict, float, int, list, str, None]]]] = Field(None, alias='contract')

    benefit_enrollments: typing.Optional[EngagementBenefitEnrollments] = Field(None, alias='benefitEnrollments')

    terminations: typing.Optional[EngagementTerminations] = Field(None, alias='terminations')

    department: typing.Optional[EngagementDepartment] = Field(None, alias='department')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
