# coding: utf-8

"""
    Endpoints

    Oyster uses OAuth2 to enable customers to grant access to their data to third party applications. Customers also need to use this API to authenticate themselves when making API requests.

    The version of the OpenAPI document: v1
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict

from oyster_python_sdk.pydantic.expenses_create_operation_key_request_receipt_amount import ExpensesCreateOperationKeyRequestReceiptAmount

class ExpensesCreateOperationKeyRequest(BaseModel):
    engagement_id: str = Field(alias='engagementId')

    name: str = Field(alias='name')

    incurred_on: date = Field(alias='incurredOn')

    category: str = Field(alias='category')

    receipt_url: str = Field(alias='receiptUrl')

    receipt_amount: ExpensesCreateOperationKeyRequestReceiptAmount = Field(alias='receiptAmount')

    description: typing.Optional[str] = Field(None, alias='description')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
