# coding: utf-8

"""
    Endpoints

    Oyster uses OAuth2 to enable customers to grant access to their data to third party applications. Customers also need to use this API to authenticate themselves when making API requests.

    The version of the OpenAPI document: v1
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict

from oyster_python_sdk.pydantic.amount import Amount
from oyster_python_sdk.pydantic.payroll_record_engagement import PayrollRecordEngagement

class PayrollRecord(BaseModel):
    engagement_id: str = Field(alias='engagementId')

    currency_code: str = Field(alias='currencyCode')

    monthly_payments_total_amount: Amount = Field(alias='monthlyPaymentsTotalAmount')

    allowances_total_amount: Amount = Field(alias='allowancesTotalAmount')

    benefits_total_amount: Amount = Field(alias='benefitsTotalAmount')

    bonuses_total_amount: Amount = Field(alias='bonusesTotalAmount')

    add_ons_total_amount: Amount = Field(alias='addOnsTotalAmount')

    taxes_total_amount: Amount = Field(alias='taxesTotalAmount')

    true_ups_total_amount: Amount = Field(alias='trueUpsTotalAmount')

    oyster_fees_total_amount: Amount = Field(alias='oysterFeesTotalAmount')

    engagement: PayrollRecordEngagement = Field(alias='engagement')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
